### ISSUE TITLE
Exception parsing font size and letter spacing with fractional em and rem units

### ISSUE THREAD

**Issue by kurtgronbech** [Carbon/Css#2]
Trying to parse any of these results in System.FormatException:

.someClass { font-size: 1.2em; } 
.someClass { font-size: 1.2rem; }

.someClass { letter-spacing: 1.2em; }
.someClass { letter-spacing: 1.2rem; }

Maybe a general problem with parsing fractional em and rem units?

Quick fix?

**Comment by iamcarbon** [comment]
@kurtgronbech Can you post the full stack trace? The library should handle em and rem unit types and decimals OK. I'm unable recreate a FormatException.

**Comment by iamcarbon** [comment]
Just updated all the numeric parsing and formatting to be Invariant. Let me know if that fixes things too.

**Comment by iamcarbon** [comment]
Closing this. Feel free to start a new issue if the issue persists.
